FROM node:22-alpine as builder

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN npm install -g pnpm@10.11.0
RUN pnpm install

COPY . .

RUN pnpm run build

# Runtime stage
FROM node:22-alpine

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./
COPY --from=builder /app/pnpm-lock.yaml ./

ENV NODE_ENV=production
EXPOSE 3000

CMD ["node", "dist/main"]
