services:
  crm_system:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crm_system
    env_file: .env
    ports:
      - "5000:3000"
    depends_on:
      crm_database:
        condition: service_healthy

  crm_database:
    image: postgres:16-alpine
    container_name: crm_database
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - crm_db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.0-alpine
    container_name: redis_cache
    restart: unless-stopped
    command: ["redis-server"]
    ports:
      - "6379:6379"
    volumes:
      - crm_cache:/data
    networks:
      - app-network



volumes:
  crm_db:
    name: crm_database
    driver: local
  crm_cache:
    name: crm_cache
    driver: local


networks:
  app-network:
    driver: bridge
